In [40]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.linear_model import LinearRegression, ElasticNet, Lasso, Ridge
from sklearn.preprocessing import KBinsDiscretizer

In [41]:
df1 = pd.read_csv('/Users/yelderiny/Projects/Dissertation/Data/processed-data.csv')
df1.head()

,pull_requests,size,contributors,age,contributor_xp,language_C,language_C#,language_C++,language_CSS,language_CoffeeScript,...,language_Shell,language_Swift,language_TeX,language_TypeScript,language_Vim Script,language_Vim Snippet,language_Vim script,language_Visual Basic .NET,language_Vue,pr_points
0,-0.531353,0.411690,-0.832546,0.124994,-1.066121,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4.0623
1,3.201163,-0.499482,2.943061,0.003687,0.476710,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,12.2630
2,-0.327467,0.189790,0.797213,-0.283266,-0.847713,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,9.9500
3,5.970774,2.983612,1.485333,-0.576075,1.402097,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,46.3520
4,1.154234,-0.122235,0.625182,-0.269044,0.544509,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,15.4270

In [42]:
df2 = pd.read_csv('/Users/yelderiny/Projects/Dissertation/Data/processed-data-outliers-capped.csv')
df2.head()

,pull_requests,size,contributors,age,contributor_xp,language_C,language_C#,language_C++,language_CSS,language_CoffeeScript,...,language_Shell,language_Swift,language_TeX,language_TypeScript,language_Vim Script,language_Vim Snippet,language_Vim script,language_Visual Basic .NET,language_Vue,pr_points
0,-0.645825,0.415549,-0.836610,0.124994,-1.117028,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4.0623
1,4.028243,-0.500406,2.968821,0.003687,0.522971,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,12.2630
2,-0.376064,0.192484,0.806022,-0.283266,-0.884864,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,9.9500
3,4.028243,3.000971,1.499578,-0.576075,1.506640,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,46.3520
4,1.584378,-0.121180,0.632633,-0.269044,0.595041,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,15.4270

In [43]:
features1 = df1.drop('pr_points', axis=1)
target1 = df1['pr_points']

In [44]:
features2 = df2.drop('pr_points', axis=1)
target2 = df2['pr_points']

In [45]:
max_error_scoring = "max_error"
neg_mean_absolute_error_scoring = "neg_mean_absolute_error"
r2_scoring = "r2"
neg_mean_squared_error_scoring = "neg_mean_squared_error"

In [46]:
models = [
    ('Linear Regression', LinearRegression()),
    ('LASSO', Lasso()),
    ('Ridge', Ridge()),
    ('Elastic Net', ElasticNet()),
    ('Random Forest', RandomForestRegressor())
]

In [47]:
for name, model in models:
    kfold = KFold(n_splits=10, shuffle=True, random_state=299)
    cv_results1 = cross_val_score(model, features1, target1, cv=kfold, scoring=max_error_scoring)
    cv_results2 = cross_val_score(model, features1, target1, cv=kfold, scoring=neg_mean_absolute_error_scoring)
    cv_results3 = cross_val_score(model, features1, target1, cv=kfold, scoring=neg_mean_squared_error_scoring)
    cv_results4 = cross_val_score(model, features1, target1, cv=kfold, scoring=r2_scoring)
    msg = f"{name} \n max error: {cv_results1.mean()} \n mean absolute error: {-cv_results2.mean()} \n max squared error: {-cv_results3.mean()} \n r2: {cv_results4.mean()}"
    print(msg, '\n', '-' * 30)

Linear Regression
 max error: -1395274224021.331
 mean absolute error: 19015678358.698837
 max squared error: 1.4275274163643572e+23
 r2: -1.0604709271033302e+21
 ------------------------------
LASSO
 max error: -34.782652302056725
 mean absolute error: 4.740234706293618
 max squared error: 47.01673355817907
 r2: 0.4570070558631981
 ------------------------------
Ridge
 max error: -33.567616475653
 mean absolute error: 4.527454851431812
 max squared error: 45.37379527499325
 r2: 0.47206250219255363
 ------------------------------
Elastic Net
 max error: -36.66654460656347
 mean absolute error: 4.866393654156682
 max squared error: 50.14372199011426
 r2: 0.42866380180515085
 ------------------------------
Random Forest
 max error: -29.807465
 mean absolute error: 3.9416244195270784
 max squared error: 38.89051301969369
 r2: 0.5516434147608007
 ------------------------------

In [48]:
for name, model in models:
    kfold = KFold(n_splits=10, shuffle=True, random_state=299)
    cv_results1 = cross_val_score(model, features2, target2, cv=kfold, scoring=max_error_scoring)
    cv_results2 = cross_val_score(model, features2, target2, cv=kfold, scoring=neg_mean_absolute_error_scoring)
    cv_results3 = cross_val_score(model, features2, target2, cv=kfold, scoring=neg_mean_squared_error_scoring)
    cv_results4 = cross_val_score(model, features2, target2, cv=kfold, scoring=r2_scoring)
    msg = f"{name} \n max error: {cv_results1.mean()} \n mean absolute error: {-cv_results2.mean()} \n max squared error: {-cv_results3.mean()} \n r2: {cv_results4.mean()}"
    print(msg, '\n', '-' * 30)

Linear Regression
 max error: -3368546206471.913
 mean absolute error: 69719650703.70192
 max squared error: 9.502538366561653e+23
 r2: -1.1112971739936976e+22
 ------------------------------
LASSO
 max error: -34.16754570498835
 mean absolute error: 4.550036137001972
 max squared error: 44.307936383242826
 r2: 0.49254423740658826
 ------------------------------
Ridge
 max error: -31.662985001476834
 mean absolute error: 4.354681957748471
 max squared error: 42.58657864745053
 r2: 0.5076552624874218
 ------------------------------
Elastic Net
 max error: -37.11326919084898
 mean absolute error: 4.746733199437033
 max squared error: 48.98438067358471
 r2: 0.4456734720337199
 ------------------------------
Random Forest
 max error: -32.941495999999994
 mean absolute error: 4.006341706605644
 max squared error: 41.99065113943396
 r2: 0.518143998357502
 ------------------------------